### ISSUE TITLE
TypeError: DicomImage is not a constructor

### ISSUE THREAD

**Issue by thejollypop** [PantelisGeorgiadis/dcmjs-imaging#1]
HI @PantelisGeorgiadis, 

First of all, Great work, I'm a fan 👍 

Wanted to ask about an error I get when trying to implement the [basic example](https://unpkg.com/dcmjs-imaging@0.0.4/build/index.html) in NODE. 
According the [Basic image rendering](https://www.npmjs.com/package/dcmjs-imaging) example, my function is: 

`const DicomImage = require("dcmjs-imaging");`
`const arrayBuffer = msg.payload; `
`var image = new DicomImage(arrayBuffer);`
`const renderedPixels = image.render(frameIndex);`
`msg.payload = renderedPixels;`
`return msg;`

However, I'm getting: `TypeError: DicomImage is not a constructor` error. 

I may be doing something wrong or missing something, but it appears to be related to `DicomImage`. 
Thanks Again!

**Comment by PantelisGeorgiadis** [comment]
Hello @thejollypop! Thank you for your kind comments! Regarding your issue, you are missing brackets around `DicomImage`. `dcmjs-imaging` exports multiple objects and, therefore, you need `const { DicomImage } = require("dcmjs-imaging");`.

**Comment by thejollypop** [comment]
Thanks! I'm getting now: `Error: Unsupported LUT pipeline photometric interpretation ` 
when using `const renderedPixels = image.render(0);`
but I guess it's related to something on my end, so we can close this issue. Thanks again!

**Comment by PantelisGeorgiadis** [comment]
My pleasure! The `Error: Unsupported LUT pipeline photometric interpretation` has to do with the data that you are passing for rendering (tip: check your `PhotometricInterpretation` DICOM tag value).

**Comment by thejollypop** [comment]
Hi @PantelisGeorgiadis ;)
With version 0.1.13, it seems that my "old code" is no longer working.
After following the basic example and adding NativePixelDecoder, I'm getting this error: `TypeError: WindowLevel.fromDicomImage is not a function`. Can you please point me what I'm missing?  Thanks!
