### ISSUE TITLE
getElement() returns undefined

### ISSUE THREAD

**Issue by david-wb** [PantelisGeorgiadis/dcmjs-imaging#10]
I'm trying to use this package in nodejs application to convert a dicom frame to a jpeg file. Unfortunately, the `image.getElement(<name>)` method is returning `undefined` for all elements. However, when I past the same dicom file into the demo site ([here](https://unpkg.com/dcmjs-imaging@0.0.4/build/index.html)), it works. 

My demo dicom file can be downloaded [here](https://drive.google.com/file/d/1eMsCmEQ5tGA5KW3m3I7gNTWHdZAD0A7A/view?usp=sharing). 

And here is a sample script to reproduce the issue. What am I doing wrong? Thanks.
```
import fs from 'fs';
import { DicomImage, WindowLevel } from 'dcmjs-imaging';

const main = () => {
  const data = fs.readFileSync('demo.dcm');
  const image = new DicomImage(data);
  console.log(
    'PhotometricInterpretation',
    image.getElement('PhotometricInterpretation'),
  );
};

main();
```

**Comment by PantelisGeorgiadis** [comment]
Hello @david-wb and thank you for your interest in dcmjs-imaging!
This library was created having in mind both browser and nodejs. Therefore, the constructor of `DicomImage` takes as input parameter an `ArrayBuffer`. You are directly passing a nodejs `Buffer`, which according to [this](https://stackoverflow.com/a/31394257/1149608), is not always equivalent. You should slice (copy) the `Buffer`'s region of the backing `ArrayBuffer`.

The code bellow worked for me:
```js
import fs from 'fs';
import { DicomImage, WindowLevel } from 'dcmjs-imaging';

const main = () => {
  const data = fs.readFileSync('demo.dcm');
  const dataArrayBuffer = data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength);
  const image = new DicomImage(dataArrayBuffer);
  console.log(
    'PhotometricInterpretation',
    image.getElement('PhotometricInterpretation'),
  );
};

main();
```

**Comment by david-wb** [comment]
Yes, I figured that out finally, but I like your solution better. Thanks for responding!
