### ISSUE TITLE
Error when rendering dicom (green & image duplicated)

### ISSUE THREAD

**Issue by chowed** [PantelisGeorgiadis/dcmjs-imaging#2]
Rendering DICOM with transfer syntax uid of JPEG Baseline shows up as green and duplicated

![image](https://user-images.githubusercontent.com/29315749/164611902-87397efd-5e78-44e2-bb02-11cbef3a0e93.png)

Any ideas as to why this might be happening?

Download the DICOM here to replicate the issue: https://drive.google.com/file/d/1s6p4GHqDIWzctZhaH9xDEaPwqDMw-nL4/view?usp=sharing

**Comment by PantelisGeorgiadis** [comment]
Thank you @chowed for reporting this! The issue has been fixed in v0.1.2 by performing the colorspace conversion of color JPEG baseline datasets, in the IJG library.

**Comment by chowed** [comment]
Hi @PantelisGeorgiadis, thank you for the explanation and quick fix. Appreciate all your contribution efforts :)
