### ISSUE TITLE
Reading incorrect path for `native-pixel-decoder.wasm`

### ISSUE THREAD

**Issue by chowed** [PantelisGeorgiadis/dcmjs-imaging#3]
Hi @PantelisGeorgiadis,

The path to the wasm file is constructed using `const wasmPath = path.join(process.cwd(), 'build', wasmFilename);`

I was wondering why this is used as opposed to something like a relative path? The library tries to read the file at MyRepo/build/native-pixel-decoder.wasm as opposed to its own.

Thanks again

**Comment by PantelisGeorgiadis** [comment]
Thank you @chowed for reporting this! Starting from v0.1.3, you can provide your own path or URL for the WebAssembly module. If not provided, the module is trying to be resolved within the same directory as the JS file.

**Comment by PantelisGeorgiadis** [comment]
Hello @chowed. Any feedback on this?

**Comment by chowed** [comment]
Hi @PantelisGeorgiadis, sorry for the late reply. It is working well, thank you once again for all your amazing work!
