### ISSUE TITLE
Export all constants

### ISSUE THREAD

**Issue by richard-viney** [PantelisGeorgiadis/dcmjs-imaging#4]
Would it be possible to have all this library's constants from `Constants.js` exported?

At the moment only `StandardColorPalette` is exported in [`index.js`](https://github.com/PantelisGeorgiadis/dcmjs-imaging/blob/master/src/index.js#L10).

Thanks!

**Comment by PantelisGeorgiadis** [comment]
Thank you @richard-viney for your comment! v0.1.3 exports all constants now!

**Comment by PantelisGeorgiadis** [comment]
Hello @richard-viney! Any feedback on this?

**Comment by richard-viney** [comment]
Works well, thanks!
