### ISSUE TITLE
Issues recognising LUT pipeline

### ISSUE THREAD

**Issue by DeanKezurer** [PantelisGeorgiadis/dcmjs-imaging#5]
Hi all,
I am currently working on analysing DICOM image data and was wondering if anyone has encountered a similar issue with the package being unable to recognise an LUTpipeline. I have implemented the code exactly from the README and am experiencing the following error when I get to _const renderingResult = image.render(renderingOpts);_:
"Error: Unsupported LUT pipeline photometric interpretation:  "
From my understanding the error message should detail the LUTpipeline being implemented at the end of the message. I am currently extracting the image's information in an ArrayBuffer format directly from a PACS server and passing it directly into _new DicomImage(pixelData);_.
Any help will be greatly appreciated.
Thanks,
Dean

**Comment by PantelisGeorgiadis** [comment]
Hello @DeanKezurer! Thank you for question! You are completely right! Next to the `Error: Unsupported LUT pipeline photometric interpretation:` you should see which unsupported interpretation you encountered. The only explanation is that your photometric interpretation tag value is empty (or the whole tag does not exist). This might be the case for bad datasets or datasets that do not contain pixel data (e.g. structured reports, encapsulated PDFs, waveforms, etc.). Please use a DICOM parser (an awesome online tool can he found [here](https://rawgit.com/cornerstonejs/dicomParser/master/examples/dumpWithDataDictionary/index.html)) to check whether your dataset actually contains a photometric interpretation and pixel data.

**Comment by DeanKezurer** [comment]
Hi @PantelisGeorgiadis. Thank you for the reply! I have managed to successfully parse the DICOM image and it's corresponding dataset contains both Pixel Data and a Photometric Interpretation. The values for each field are as follows:
- PixelData: Proxy {0: ArrayBuffer(....)}
- PhotometricInterpretation: "RGB"

Is there any other reason that the render function may not be working as intended? Thank you for your help.

**Comment by PantelisGeorgiadis** [comment]
Hello @DeanKezurer! Hmmmm, that is strange... I just verified that datasets with `RGB` Photometric Interpretation are rendered properly. Do you mind anonymizing your dataset and share it so we can further investigate?

**Comment by PantelisGeorgiadis** [comment]
Hello @DeanKezurer! Did you manage to render your dataset?

**Comment by PantelisGeorgiadis** [comment]
@DeanKezurer, I'm closing this issue now. If you still have issues rendering your datasets, please open a new issue.

**Comment by desiprisg** [comment]
Hey @PantelisGeorgiadis . I'm facing the same issue. I'm have no experience with DICOM files, but using some samples from https://www.dicomlibrary.com, like this one: https://www.dicomlibrary.com/meddream/?study=1.3.6.1.4.1.44316.6.102.1.202309138320793.7061854338476473978984
I get the same error with an empty value.

**Comment by PantelisGeorgiadis** [comment]
Hello @desiprisg! Thank you for your interest in `dcmjs-imaging`!
I exported the study from the link you provided and successfully rendered the downloaded files (4 files in total) in the [rendering example page](https://unpkg.com/dcmjs-imaging/build/index.html). Are there any other files accompanying the study? Often, there are files that contain non-imaging, supporting information, that `dcmjs-imaging` can't render.

**Comment by desiprisg** [comment]
That's interesting. I tried doing it in a node environment. That could be the differentiating factor.

**Comment by PantelisGeorgiadis** [comment]
Hello @desiprisg! I just created a quick Node.JS project (node version 16.13.1) and used it on your data. It works as expected!
I'm attaching it bellow so you can compare it with yours. Please remember to put your files inside the project's file structure.

[dcmjs-imaging-test.zip](https://github.com/user-attachments/files/20627761/dcmjs-imaging-test.zip)
