### ISSUE TITLE
'WindowLevel' old code issue

### ISSUE THREAD

**Issue by thejollypop** [PantelisGeorgiadis/dcmjs-imaging#6]
Hi @PantelisGeorgiadis ;)
With version 0.1.13, it seems that my "old code" is no longer working .
After following the basic example and adding `NativePixelDecoder`, I'm getting this error: `TypeError: WindowLevel.fromDicomImage is not a function`. Can you please point me what I'm missing? Thanks! My Old Code:

```
const buf = msg.payload;
const { DicomImage, WindowLevel } = dcmjsImaging;

msg.payload = renderFile(buf.buffer);
msg.payload.jimp = {
w: msg.payload.image.width, h: msg.payload.image.height, background: "black"}
return msg;

function renderFile(arrayBuffer) {
// debugger
let frame = 0;
const image = new DicomImage(arrayBuffer);
const windowLevels = WindowLevel.fromDicomImage(image);
const windowLevel =
windowLevels.length > 0 ? windowLevels[0] : createDefaultWindowLevel(image);

const result = {
    framecount: image.getNumberOfFrames()
}

result.image = renderFrame(image, frame, windowLevel);
return result;
}

function renderFrame(image, frame, windowLevel) {

const result = {
    height: image.getHeight(),
    width: image.getWidth(),
    bitmap: null
}

try {

    const renderedPixels = new Uint8Array(image.render(frame, windowLevel));
    // const imageData = ctx.createImageData(image.getWidth(), image.getHeight());
    // const canvasPixels = imageData.data;
    const canvasPixels = [];
    for (let i = 0; i < 4 * image.getWidth() * image.getHeight(); i++) {
        canvasPixels[i] = renderedPixels[i];
    }
    // ctx.putImageData(imageData, 0, 0);
    result.bitmap = canvasPixels;
    return result;
} catch (err) {
    throw err;
}
}

function createDefaultWindowLevel(image) {
const photometricInterpretation = image.getElement('PhotometricInterpretation');
if (!photometricInterpretation) {
return;
}
if (['MONOCHROME1', 'MONOCHROME2'].indexOf(photometricInterpretation) == -1) {
return;
}
const bitsStored = image.getElement('BitsStored');
if (!bitsStored) {
return;
}
const pixelRepresentation = image.getElement('PixelRepresentation') || 0;
const signed = pixelRepresentation !== 0;

const minValue = signed ? -(1 << (bitsStored - 1)) : 0;
const maxValue = signed ? (1 << (bitsStored - 1)) - 1 : (1 << bitsStored) - 1;

return new WindowLevel(maxValue - minValue, (minValue + maxValue) / 2);
}

```

**Comment by PantelisGeorgiadis** [comment]
Hello @thejollypop and thank you for your comment! You are perfectly right. Version 0.1.13 introduced some breaking changes to avoid circular dependencies among classes. One of the changes is that `WindowLevel.fromDicomImage()` was converted to `WindowLevel.fromDicomImageElements()`. The new function does not accept a `DicomImage` object but rather the elements of it, obtained by `getElements()`. Therefore, you need to update your `WindowLevel.fromDicomImage(image);` to `WindowLevel.fromDicomImageElements(image.getElements());`. <br>
I noticed in your code that you are trying to calculate the `WindowLevel` and pass it into the rendering function. However, the rendering function has been updated quite some time now to calculate the optimal `WindowLevel`, if you skip that parameter while calling the rendering function. I suggest you to update `image.render(frame, windowLevel)` to `image.render(frame)`.

**Comment by thejollypop** [comment]
Thanks @PantelisGeorgiadis it does help:) However now I'm getting a blank decoded image and for other DICOM files  I get `Error: NativePixelDecoder module is not initialized`. To make this work, is `NativePixelDecoder` needed? Thanks

**Comment by PantelisGeorgiadis** [comment]
If your images are compressed, yes, you need to initialize `NativePixelDecoder`.

**Comment by thejollypop** [comment]
Indeed, the initialization solved the error. Now just need to figure out why the decoded image is blank. Thank you, I guess this issue can be closed

**Comment by PantelisGeorgiadis** [comment]
Perfect! Let me know about the blank decoded image issue!
